# Generated by Django 5.2.8 on 2025-11-25 00:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0002_alter_worldtemplate_max_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_agents', models.IntegerField(default=5, help_text='Número total de agentes en la simulación')),
                ('num_fumigators', models.IntegerField(default=3, help_text='Número de agentes fumigadores')),
                ('num_scouts', models.IntegerField(default=2, help_text='Número de agentes scouts')),
                ('max_steps', models.IntegerField(default=1000, help_text='Número máximo de pasos de simulación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutándose'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('steps_executed', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('fields_fumigated', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=dict, help_text='Resultados detallados de la simulación')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='world.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(help_text='ID único del agente en AgentPy', max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('fumigator', 'Fumigador'), ('scout', 'Explorador')], default='fumigator', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_z', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='idle', help_text='Estado actual del agente (idle, moving, fumigating, etc.)', max_length=50)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('fields_fumigated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional del agente')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='world.world')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['world', 'is_active'], name='agents_agen_world_i_6d8104_idx'), models.Index(fields=['agent_id'], name='agents_agen_agent_i_f18e23_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlackboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(help_text="Tipo de entrada (ej: 'field_discovered', 'agent_status', 'coordination')", max_length=50)),
                ('content', models.JSONField(default=dict, help_text='Contenido de la entrada')),
                ('agent_id', models.CharField(blank=True, help_text='ID del agente que creó la entrada', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Cuándo expira esta entrada', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si la entrada está activa')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard_entries', to='world.world')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['world', 'entry_type', 'is_active'], name='agents_blac_world_i_cdbbc2_idx'), models.Index(fields=['agent_id', 'is_active'], name='agents_blac_agent_i_0df173_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlackboardTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_x', models.IntegerField(help_text='Coordenada X del campo a fumigar')),
                ('position_z', models.IntegerField(help_text='Coordenada Z del campo a fumigar')),
                ('infestation_level', models.IntegerField(help_text='Nivel de infestación del campo (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('assigned_agent_id', models.CharField(blank=True, help_text='ID del agente asignado (de AgentPy)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional de la tarea')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='world.world')),
            ],
            options={
                'ordering': ['-priority', '-infestation_level', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='agents_blac_status_19bf2a_idx'), models.Index(fields=['world', 'status'], name='agents_blac_world_i_f55431_idx')],
            },
        ),
    ]
