# Generated by Django 5.2.8 on 2025-11-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='max_steps',
            field=models.IntegerField(default=300, help_text='Número máximo de pasos de simulación'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='num_agents',
            field=models.IntegerField(default=6, help_text='Número total de agentes en la simulación'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='num_fumigators',
            field=models.IntegerField(default=5, help_text='Número de agentes fumigadores'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='num_scouts',
            field=models.IntegerField(default=1, help_text='Número de agentes scouts'),
        ),
    ]
