# Generated by Django 5.2.8 on 2025-12-03 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_simulation_max_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duración total de la simulación en segundos', null=True)),
                ('efficiency_score', models.FloatField(blank=True, help_text='Eficiencia: campos fumigados por paso', null=True)),
                ('tasks_per_step', models.FloatField(blank=True, help_text='Tareas completadas por paso', null=True)),
                ('success_rate', models.FloatField(blank=True, help_text='Porcentaje de tareas completadas (0-100)', null=True)),
                ('completion_percentage', models.FloatField(blank=True, help_text='Porcentaje de campos fumigados (0-100)', null=True)),
                ('initial_infested_fields', models.IntegerField(default=0, help_text='Número de campos con infestación al inicio')),
                ('final_infested_fields', models.IntegerField(default=0, help_text='Número de campos con infestación al final')),
                ('infestation_reduction_percentage', models.FloatField(blank=True, help_text='Porcentaje de reducción de infestación (0-100)', null=True)),
                ('average_initial_infestation', models.FloatField(blank=True, help_text='Nivel promedio de infestación inicial', null=True)),
                ('average_final_infestation', models.FloatField(blank=True, help_text='Nivel promedio de infestación final', null=True)),
                ('avg_tasks_per_agent', models.FloatField(blank=True, help_text='Promedio de tareas completadas por agente', null=True)),
                ('avg_fields_per_agent', models.FloatField(blank=True, help_text='Promedio de campos fumigados por agente', null=True)),
                ('max_tasks_by_agent', models.IntegerField(default=0, help_text='Máximo de tareas completadas por un solo agente')),
                ('min_tasks_by_agent', models.IntegerField(default=0, help_text='Mínimo de tareas completadas por un solo agente')),
                ('avg_time_per_task', models.FloatField(blank=True, help_text='Tiempo promedio por tarea en segundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional y estadísticas detalladas')),
                ('simulation', models.OneToOneField(help_text='Simulación asociada', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='agents.simulation')),
            ],
            options={
                'verbose_name': 'Estadísticas de Simulación',
                'verbose_name_plural': 'Estadísticas de Simulaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['simulation'], name='agents_simu_simulat_11085c_idx')],
            },
        ),
    ]
