# Generated by Django 5.2.8 on 2025-11-12 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('width', models.IntegerField(default=20)),
                ('height', models.IntegerField(default=20)),
                ('road_branch_chance', models.FloatField(default=0.6)),
                ('max_road_length', models.IntegerField(default=10)),
                ('field_chance', models.FloatField(default=0.9)),
                ('field_growth_chance', models.FloatField(default=0.55)),
                ('min_fields', models.IntegerField(default=5)),
                ('min_roads', models.IntegerField(default=10)),
                ('max_attempts', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('grid', models.JSONField()),
                ('crop_grid', models.JSONField()),
                ('infestation_grid', models.JSONField()),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.worldtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
