# Generated by Django 5.2.8 on 2025-11-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldtemplate',
            name='max_attempts',
            field=models.IntegerField(default=30),
        ),
    ]
